name: explore
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # network requests
  dio: ^4.0.6

  # service locator
  get_it: ^7.2.0

  # showing overlays
  overlay_support: ^2.0.1

  # state management
  provider: ^6.0.3

  #cached image
  cached_network_image: ^3.2.1

  # functional programming
  dartz: ^0.10.1

  # error and info notification widget
  another_flushbar: ^1.12.29

  # local storage
  sqflite: ^2.2.0+3

  # path
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/svgs/

  # fonts:
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Bold.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Medium.ttf
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-Light.ttf
